Repository h2oai/mlops-dai-runtimes, pull requests merged in 2024-08, with the labels that each got.

#396 chore: try to make use of dependabot
  .github/dependabot.yml
  gradle.properties
  gradle/mixins/dependencies.gradle
Labels: type/chore, area/chore

#399 chore: update image to fix vulnerabilities
  gradle.properties
Labels: area/chore, type/security

#398 chore: Enable image security scan (Trivy & Prisma) workflow
  .github/workflows/image-build.yml
  .github/workflows/image-security-scan.yml
Labels: security, type/chore

#400 fix: don't run as root
  aws-sagemaker-hosted-scorer/build.gradle
  gcp-cloud-run/build.gradle
  gcp-vertex-ai-mojo-scorer/build.gradle
  local-rest-scorer/build.gradle
Labels: area/chore, type/security

#403 chore: Update gradle
  build.gradle
  gradle/wrapper/gradle-wrapper.jar
  gradle/wrapper/gradle-wrapper.properties
  gradlew
  gradlew.bat
Labels: type/update, area/chore

#404 chore: Update spring
  gradle.properties
Labels: area/chore, type/security

#406 chore: Update component new name in references
  README.md
  docs/gcp.md
  gcp-cloud-run/README.md
  gcp-vertex-ai-mojo-scorer/README.md
  mkdocs.yml
  settings.gradle
Labels: type/chore

#405 chore: Refine CICD with cleanups
  .github/workflows/ci.yml
  .github/workflows/image-build.yml
  .github/workflows/image-publish.yml
Labels: type/chore
